### ISSUE TITLE
Please remove this repo from public access

### ISSUE THREAD

**Issue by ghost** [jitendra-artifex/magento#1]
Hello, 

On behalf of aheadWorks Co. I am demanding you to remove from public access this repository (https://github.com/jitendra-artifex/magento/) or at least the following paths:
https://github.com/jitendra-artifex/magento/tree/master/app/code/local/AW
https://github.com/jitendra-artifex/magento/tree/master/app/code/community/AW

Note, the [license](https://ecommerce.aheadworks.com/AW-LICENSE.txt) of the products by aheadWorks is not Open Source, and it prohibits anyone to place the source files of our products into a publicly accessible repository. This violation of the aheadWorks EULA which may also be considered as a distribution, so if the repository is still accessible after 48 hours, we will submit a DMCA claim on Github and may also initiate a legal action against you.

Best Regards,

**Comment by jitendra-artifex** [comment]
Hello,

Please checkout the public repository I was remove magento set-up as per your instruction.

Best Regards,
